os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 24june_100k13_05
      script: 
        - echo "condition with job tt"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
